**SINGLE NEURON FUNDAMENTALS**

**FORWARD PASS**

In [6]:
import numpy as np
import pandas as pd

In [7]:
datapoint = np.array([0.05,0.37,0.46])
weights = np.array([0.4,0.2,0.1])
bias = 0.6769

In [8]:
z = np.dot(datapoint,weights) + bias
z

np.float64(0.8169)

In [9]:
sigmoid = 1 / (1 + np.exp(-z)) #Activation function
print(sigmoid)

0.6935779002102053


In [10]:
weights = np.array([[0.4, 0.2, 0.1],[0.1, 0.5, 0.3],[0.2, 0.2, 0.6],[0.7, 0.1, 0.1]])

In [11]:
bias = np.array([0.67 , 0.69 , 0.66 , 0.68])

In [12]:
z = np.dot(weights,datapoint) + bias
print(z)

[0.81  1.018 1.02  0.798]


In [13]:
print(z.shape)

(4,)


In [14]:
a1 = 1 / (1 + np.exp(-z))
a1

array([0.6921095 , 0.73458284, 0.7349726 , 0.6895465 ])

In [15]:
w2 = np.array([[0.3,0.5,0.7,0.1],[0.2,0.5,0.6,0.3]])
b2 = np.array([0.5,0.9])
z2 = np.dot(w2,a1) + b2
print(z2.shape)
a2 = 1 / (1 + np.exp(-z2))
print(a2.shape)
print(a2)

(2,)
(2,)
[0.84001769 0.88630693]


**BACKPROPAGATION AND LOSS FUNCTION**

In [16]:
y = [1,0]

In [17]:
#binary_Cross_entropy_loss = (-y * log(p) + (1-y) * log)

In [18]:
loss1 = -(y[0] * np.log(a2[0]) + (1-y[0]) * np.log(1-a2[0]))
print(loss1)
loss2 = -(y[1] * np.log(a2[1]) + (1-y[1]) * np.log(1-a2[1]))
print(loss2)
total_loss = loss1 + loss2
print(total_loss)

0.17433232197717316
2.17425280066088
2.348585122638053


**GRADIENT DESCENT**

In [19]:
#dLoss/dp = −(y/p) + (1−y)/(1−p)

In [20]:
gradient_descent1 = -(y[0]/a2[0]) + (1-y[0])/(1-a2[0])
print(gradient_descent1)
gradient_descent2 = -(y[1]/a2[1]) + (1-y[1])/(1-a2[1])
print(gradient_descent2)

-1.1904511131598388
8.79561059182975


In [21]:
da2_1 = a2[0] * (1 - a2[0])
da2_2 = a2[1] * (1 - a2[1])
print(da2_1)
print(da2_2)
print((0.99)*(1-0.99))
print((0.01)*(1-0.01))

0.13438796713642043
0.10076695840686493
0.00990000000000001
0.0099


In [22]:
actual_gradient_descent = gradient_descent1 * da2_1  * a1[0]
print(actual_gradient_descent)

-0.11072527386102042


In [23]:
dz2 = []
dz2.append(gradient_descent1 * da2_1)
dz2.append(gradient_descent2 * da2_2)
print(dz2)

[np.float64(-0.15998230507283953), np.float64(0.8863069266698891)]


In [24]:
np.outer(dz2,a1)

array([[-0.11072527, -0.11752026, -0.11758261, -0.11031524],
       [ 0.61342145,  0.65106586,  0.65141131,  0.61114984]])

In [25]:
db2 = dz2

In [30]:
dLoss_da1 = np.dot(dz2,w2)
print(dLoss_da1.shape)
dLoss_da1

(4,)


array([0.12926669, 0.36316231, 0.41979654, 0.24989385])

In [37]:
da1_dz1 = a1 * (1 - a1)
print(da1_dz1.shape)
print(da1_dz1)

(4,)
[0.21309394 0.19497089 0.19478788 0.21407212]


In [38]:
delta1 = dLoss_da1 * da1_dz1
print(delta1.shape)
print(delta1)

(4,)
[0.02754595 0.07080608 0.08177128 0.05349531]


In [39]:
dw1 = np.outer(delta1,datapoint)
print(dw1.shape)
print(dw1)

(4, 3)
[[0.0013773  0.010192   0.01267114]
 [0.0035403  0.02619825 0.0325708 ]
 [0.00408856 0.03025537 0.03761479]
 [0.00267477 0.01979326 0.02460784]]


In [40]:
db1 = delta1